"""add column is_archive to user table

Revision ID: 8e170a7ed64c
Revises: cb17ff015fa2
Create Date: 2022-01-10 00:50:45.035714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e170a7ed64c'
down_revision = 'cb17ff015fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_archive', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_archive')
    # ### end Alembic commands ###
